name: 02 - dbt Build e Testes

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  dbt_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dbt e dependências
        run: |
          python -m pip install --upgrade pip
          pip install dbt-duckdb

      - name: Instalar pacotes do dbt
        run: |
          dbt deps --project-dir $GITHUB_WORKSPACE/data_eng/transform --profiles-dir $GITHUB_WORKSPACE
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}

      - name: Executar dbt Build
        run: |
          dbt build --project-dir $GITHUB_WORKSPACE/data_eng/transform --profiles-dir $GITHUB_WORKSPACE
        env:
          MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}