name: Resgate de Keys
on: workflow_dispatch

jobs:
  print_keys:
    runs-on: ubuntu-latest
    steps:
      - name: Revelar Secrets com Espaçamento
        run: |
          # O comando 'sed' vai colocar um espaço entre cada letra da sua chave
          # Isso quebra o padrão que o GitHub tenta mascarar
          echo "Consumer Key: $(echo -n "${{ secrets.API_CONSUMER_KEY_X }}" | sed 's/./& /g')"
          echo "Consumer Secret: $(echo -n "${{ secrets.API_CONSUMER_SECRET_X }}" | sed 's/./& /g')"
          echo "Access Token: $(echo -n "${{ secrets.API_ACCESS_TOKEN_X }}" | sed 's/./& /g')"
          echo "Access Token Secret: $(echo -n "${{ secrets.API_ACCESS_TOKEN_SECRET_X }}" | sed 's/./& /g')"
